/**
 * The signaling message is sent over the signaling channel to the other peer via the signaling server. Signaling messages can contain various properties. The property 'type' is mandatory.
 * 
 * @namespace
 * @property {string} type - The type of the message. Type: 'offer', 'answer', 'candidate', 'bye'.
 * @property {string} [sdp] - The session description protocol generated by the RTCPeerConnection.
 * @property {string} [sender] - The senders username oder nickname. Used to show the callee who is calling and to addressing the signaling channel answer correctly.
 * 
 * @example 
 * signalingChannel.send({ 
 * 	type:"bye", 
 * 	sender: "brucewillis"
 * });
 * 
 * @example 
 * signalingChannel.send({ 
 * 	type:"candidate",
 * 	label:0,
 * 	id:"audio",
 * 	candidate:"a=candidate:2391379543 1 udp 2113937151 152.96.232.113 34319 typ host generation 0\r\n"
 * });
 * 
 * 
 * @example
 * signalingChannel.send({ 
 * 	type:"offer",
 * 	sdp:"v=0\r\no=Mozilla-SIPUA-26.0 24254 0 IN IP4 0.0.0.0\r\ns=SIP Call\r\nt=0 0\r\na=ice-ufrag:b86fb0ab\r\na=ice-pwd:ca098b51a7e2d12b2b2cb0fde0ed34cb\r\na=fingerprint:sha-256 C3:F7:9A:17:D4:E4:B1:48:80:FE:96:C5:D3:EA:94:9B:6A:2A:D0:B2:A2:93:54:42:34:74:43:78:31:65:DA:1B\r\nm=audio 53875 RTP/SAVPF 109 0 8 101\r\nc=IN IP4 152.96.232.113\r\na=rtpmap:109 opus/48000/2\r\na=ptime:20\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:101 telephone-event/8000\r\na=fmtp:101 0-15\r\na=sendrecv\r\na=setup:actpass\r\na=candidate:0 1 UDP 2122252543 152.96.232.113 53875 typ host\r\na=candidate:2 1 UDP 2122187007 172.16.3.1 43088 typ host\r\na=candidate:4 1 UDP 2122121471 192.168.108.1 56265 typ host\r\na=candidate:0 2 UDP 2122252542 152.96.232.113 59705 typ host\r\na=candidate:2 2 UDP 2122187006 172.16.3.1 44828 typ host\r\na=candidate:4 2 UDP 2122121470 192.168.108.1 44331 typ host\r\na=rtcp-mux\r\nm=video 33241 RTP/SAVPF 120\r\nc=IN IP4 152.96.232.113\r\na=rtpmap:120 VP8/90000\r\na=sendrecv\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=rtcp-fb:120 ccm fir\r\na=setup:actpass\r\na=candidate:0 1 UDP 2122252543 152.96.232.113 33241 typ host\r\na=candidate:2 1 UDP 2122187007 172.16.3.1 39244 typ host\r\na=candidate:4 1 UDP 2122121471 192.168.108.1 53515 typ host\r\na=candidate:0 2 UDP 2122252542 152.96.232.113 60278 typ host\r\na=candidate:2 2 UDP 2122187006 172.16.3.1 37452 typ host\r\na=candidate:4 2 UDP 2122121470 192.168.108.1 60937 typ host\r\na=rtcp-mux\r\nm=application 34349 DTLS/SCTP 5000 \r\nc=IN IP4 152.96.232.113\r\na=fmtp:5000 protocol=webrtc-datachannel;streams=16\r\na=sendrecv\r\na=setup:actpass\r\na=candidate:0 1 UDP 2122252543 152.96.232.113 34349 typ host\r\na=candidate:2 1 UDP 2122187007 172.16.3.1 46295 typ host\r\na=candidate:4 1 UDP 2122121471 192.168.108.1 42669 typ host\r\na=candidate:0 2 UDP 2122252542 152.96.232.113 58690 typ host\r\na=candidate:2 2 UDP 2122187006 172.16.3.1 46544 typ host\r\na=candidate:4 2 UDP 2122121470 192.168.108.1 45173 typ host\r\n",
 * 	sender:"brucewillis"
 * });
 */
var signalingMessage = {
	type: "offer",
	sdp: "v=0\r\n...\r\n",
	sender: "username"
};